### ISSUE TITLE
TAS_Toolkit: Error Pull from TBD

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#160]
There is error when pulling from native TAS TBD file

```
Warning: Compute.RunCaller operation failed. 
System.InvalidCastException: OleAut reported a type mismatch.
   at Microsoft.Win32.OAVariantLib.ChangeTypeEx(Variant& result, Variant& source, Int32 lcid, IntPtr typeHandle, Int32 cvType, Int16 flags)
   at Microsoft.Win32.OAVariantLib.ChangeType(Variant source, Type targetClass, Int16 options, CultureInfo culture)
   at System.OleAutBinder.ChangeType(Object value, Type type, CultureInfo cultureInfo)
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at TBD.IConstruction.get_additionalHeatTransfer()
   at BH.Engine.TAS.Convert.ToBHoM(Construction tbdConstruction)
   at BH.Engine.TAS.Convert.ToBHoM(buildingElement tbdElement, zoneSurface tbdSurface)
   at BH.Adapter.TAS.TasTBDAdapter.ReadBuildingElements(List`1 ids)
   at BH.Adapter.TAS.TasTBDAdapter.Read()
   at BH.Adapter.TAS.TasTBDAdapter.Read(Type type, IList indices)
   at BH.Adapter.BHoMAdapter.Read(FilterQuery query)
   at BH.Adapter.TAS.TasTBDAdapter.Pull(IQuery query, Dictionary`2 config)
This component failed to run properly. Output data is calculated but cannot be set.
Value cannot be null.
Parameter name: source
```

Test file including TBD and Dynamo: 
[TAS_Toolkit Error Pull from TBD Issue160.zip](https://github.com/BHoM/TAS_Toolkit/files/2922980/TAS_Toolkit.Error.Pull.from.TBD.Issue160.zip)

**Comment by FraserGreenroyd** [comment]
Can I check if you have encountered this error in Grasshopper as well to isolate that this is not a Dynamo problem?

**Comment by michaldengusiak** [comment]
ok same here
![image](https://user-images.githubusercontent.com/26113670/53694922-f411fe80-3dac-11e9-8e0f-5be6b85fda98.png)
I will investigate..

**Comment by michaldengusiak** [comment]
ok issue is here in TAS_Toolkit... but will check if not affected by other change

https://github.com/BHoM/TAS_Toolkit/blob/260da4088f67d1515ce8973839824ba6697c3f8b/TAS_TBDAdapter/TASTBDAdapter.cs#L90

not sure why we are not referencing:
`                            returnObjs.AddRange(Read());`

Error is with these two... BuildingElements and Construction, as it works when commented
https://github.com/BHoM/TAS_Toolkit/blob/260da4088f67d1515ce8973839824ba6697c3f8b/TAS_TBDAdapter/CRUD/Read.cs#L77
https://github.com/BHoM/TAS_Toolkit/blob/260da4088f67d1515ce8973839824ba6697c3f8b/TAS_TBDAdapter/CRUD/Read.cs#L78

when I change to read and switch off `BuildingElements `and `Construction `it works.
Ok we have now isolated issue.

**Comment by michaldengusiak** [comment]
ok...I found issue, it is related to version 9.4.4
Let me confirm this on Monday.
Please leave this issue for me.

**Comment by FraserGreenroyd** [comment]
I have assigned @mariatjader as she is primarily going to be working on this toolkit during March so we need to keep up to date with changes. @mariatjader won't have upgraded TAS yet.

I will schedule a meeting for us to discuss this issue then - this is not just a development issue but needs a wider discussion as to which version of TAS we intend to support for TAS Toolkit. We need to rectify for March sprint, but we don't want to do too much abortive work. I'll send a meeting invite shortly.

**Comment by michaldengusiak** [comment]
ok this is now fixed with new version update,
